### ISSUE TITLE
Log more information when warning threshold is exceeded

### ISSUE THREAD

**Issue by LiteracyFanatic** [hakavlad/nohang#102]
Right now triggering a warning just outputs `Warning threshold exceeded`. It would be nice to get more detailed information about which threshold was exceeded and by how much similar to the output when corrective action is taken.

**Comment by hakavlad** [comment]
Hi! https://github.com/hakavlad/nohang/commit/ac2572190ccbaeca83d76295e391cbaabb57f71a
```
Monitoring has started!
Warning threshold exceeded
Memory info, MiB:
  total=9782, used=9121, free=337, available=0, shared=173, buffers=1, cache=324,
  swap_total=48909, swap_used=4854, swap_free=44055
Memory pressure (system-wide):
  some avg10=28.59 avg60=6.01 avg300=2.10
  full avg10=20.69 avg60=4.34 avg300=1.40
Executing Command-1 ['sudo', '-u', 'user', 'env', 'DISPLAY=:0', 'DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus', 'notify-send', '--icon=dialog-warning', '--app-name=nohang', 'Low memory', 'Save your unsaved data!\nClose unused apps!'] with timeout 30s in Thread-2
```
Now nohang logs meminfo and memory pressure at `Warning threshold exceeded`.

**Comment by LiteracyFanatic** [comment]
Awesome! Thanks. That will be very useful for troubleshooting.
