### ISSUE TITLE
Spurious warnings with small swap

### ISSUE THREAD

**Issue by JcKlomp** [hakavlad/nohang#105]
I'm using nohang-desktop on fedora (I believe with the default nohang-desktop configuration) on a system with 32 GB ram and a 512 MB swap partition (I know the latter is a bit of a silly number considering the former but on the other hand why not, and until recently there were some gigs of hdd swap there too) with zswap enabled.

During normal usage the swap partition will fill up completely leading to constant nohang warnings telling me the system is low on memory and I need to save and close my apps, while in reality there still are tons of available memory.

```
Warning threshold exceeded
Memory info, MiB:
  total=32082, used=18167, free=3437, available=4085, shared=4538, buffers=0, cache=10477,
  swap_total=500, swap_used=500, swap_free=0
Memory pressure (system-wide):
  some avg10=0.03 avg60=0.12 avg300=0.19
  full avg10=0.03 avg60=0.12 avg300=0.19
```

I've set `warning_threshold_min_swap = 0 %` but the warnings keep happening every `min_post_warning_delay`, so it seems there is no way to disable a specific warning item and I need to resort to disabling the warning feature all together.

**Comment by hakavlad** [comment]
Hi! If you hava a lot of RAM, may be a good idea to decrease all thresholds. For example,

```
warning_threshold_min_mem  = 1000M
warning_threshold_min_swap = 100%

soft_threshold_min_mem = 500M
soft_threshold_min_swap = 100%

hard_threshold_min_mem = 200M
hard_threshold_min_swap = 100%
```

If you often have swap_used=swap_total, a maybe a good idea to ignore swap thresholds at all.

**Comment by hakavlad** [comment]
BTW, earlyoom on Fedora uses soft threshold for memory 4%, but not more than 400M.
https://src.fedoraproject.org/rpms/earlyoom/blob/master/f/earlyoom-fedora-options.patch#_21

**Comment by JcKlomp** [comment]
Thanks, setting all swap thresholds to 100% did the trick! (Must say the 100% setting feels quite counterintuitive for ignoring the parameter.)
I now only get anticipated warnings when the mem fills up.

I'm still curious about whether nohang has taken any corrective actions and whether it should have since the hard threshold also has been exceeded. Or does it require that all hard_threshold are exceeded before actions are taken?

**Comment by hakavlad** [comment]
>it require that all hard_threshold are exceeded before actions are taken?

Both (mem and swap) thresholds must be excceded to implement corrective action. It works like follow:
```
while True:
    if hard_threshold_min_mem <= MemAvailable and hard_threshold_min_swap <= SwapFree:
        implement_corrective_action(SIGKILL)
        continue
    if soft_threshold_min_mem <= MemAvailable and soft_threshold_min_swap <= SwapFree:
        implement_corrective_action(SIGTERM)
        continue
    if warning_threshold_min_mem <= MemAvailable and warning_threshold_min_swap <= SwapFree:
        implement_warning()
        continue
    sleep()
```
> 100% setting feels quite counterintuitive for ignoring the parameter

`SwapFree <= 100%` is always True, that's why `SwapFree` value is not matter if threshold <= 100%.
