### ISSUE TITLE
nohang:1180: SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by FabioPedretti** [hakavlad/nohang#107]
Installed nohang 0.1-1.1 from Ubuntu 20.10 official package. Running it I get:
```
$ nohang
/usr/sbin/nohang:1180: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is 0:
/usr/sbin/nohang:1341: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 2:
The path to the config: /etc/nohang/nohang.conf
Monitoring started!
```

Having a quick look at the upstream code this is likely already fixed, so think this as a suggestion to make a new official release, so that distros can get the latest fixes!

Thanks!

**Comment by hakavlad** [comment]
Ok, thanks!

**Comment by hakavlad** [comment]
@FabioPedretti I don't recommend to use this outdated and buggy 0.1 release. See https://github.com/hakavlad/nohang/blob/master/CHANGELOG.md

I recommend to use the latest snapshot. 0.2 coming soon.

**Comment by FabioPedretti** [comment]
Great, thanks for the quick reply!

**Comment by FabioPedretti** [comment]
BTW I can confirm the SyntaxWarnings are fixed in the git version, hopefully a new release will be released soon, official Debian/Ubuntu packages updated and their users will get latest code. In the meantime see #73 for updated packages.

**Comment by FabioPedretti** [comment]
Let's close this one, since it's actually fixed.
