### ISSUE TITLE
do not kill calamares no matter the memory situation

### ISSUE THREAD

**Issue by librewish** [hakavlad/nohang#109]
well we have seen this lot of times calamres use a lot of memory while installing the os
if possible whitelist calamares in nohang

so it wont kill calamares

**Comment by hakavlad** [comment]
How much memory did Calamares use? It was about 250M in my case.

**Comment by hakavlad** [comment]
You may also increase zram disksize during installation.

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/3a0fd4f051d63aa6f9018011513c02a5e3ebe384
