### ISSUE TITLE
Allow prefer_regex and avoid_regex to match cmdline

### ISSUE THREAD

**Issue by schumar** [hakavlad/nohang#11]
I'd rather have `nohang` kill a single Firefox tab instead of the whole browser. Sadly, both processes have the same `name`, so I can't use `prefer_regex` for that.

If `nohang` would give me some way to also match the cmdline-params (can get those from `/proc/$pid/cmdline`), I would be able to give processes with an `-childID` "preferred" treatment :)

Not sure if this should require extra config-options (`enable_cmdline`, `prefer_cmdline_regex`,...) are just be included in the standard behaviour.

**Comment by hakavlad** [comment]
Thank you for this question!  I plan to improve support regex matching in future.
This section should be completely redesigned.
I would like the configuration to look like this:
```
$MODIFY_BADNESS_BY_RE_MATCH_UID         -200  ///  333|33|1000
$MODIFY_BADNESS_BY_RE_MATCH_UID        -2000  ///  0
$MODIFY_BADNESS_BY_RE_MATCH_CMDLIME      100  ///  /usrr/lib/firefox/firefox
$MODIFY_BADNESS_BY_RE_MATCH_USERNAME     300  ///  user1|user2
$MODIFY_BADNESS_BY_RE_MATCH_PROCESSNAME -400  ///  Xorg|sshd
```

**Comment by hakavlad** [comment]
One of the problems is that cmdlines sometimes contains null byte.

**Comment by schumar** [comment]
That NUL is used to separate the arguments. I *guess* it would be perfectly ok to just replace all NULs with SPCs (can't think of a case right now where I need to differentiate between a program called `foo` wih a parameter `bar baz` and a program called `foo bar` with a parameter `baz`)

**Comment by hakavlad** [comment]
@schumar 
adding cmdline re matching in progress, https://github.com/hakavlad/nohang#changelog

**Comment by hakavlad** [comment]
@schumar Done. Welcome to testing!

**Comment by hakavlad** [comment]
matching with UID also implemented

**Comment by hakavlad** [comment]
Now seems like all works well.
```
                    # this default pattern for prefer childs of chromium & firefox
prefer_re_cmdline = renderer|childID
prefer_cmd_factor = 10

avoid_re_cmdline = ^/usr/lib/virtualbox
avoid_cmd_factor = 3
```

**Comment by hakavlad** [comment]
new flexible syntax

```
    4.1 Matching process names with RE patterns

    Valid values are True and False.

regex_matching = False

    Syntax:

    @PROCESSNAME_RE badness_adj /// RE_pattern

    New badness value will be += badness_adj

    It is possible to compare multiple patterns
    with different badness_adj values.

    Example:

@PROCESSNAME_RE -100 /// ^Xorg$
@PROCESSNAME_RE -500 /// ^sshd$
@PROCESSNAME_RE  300 /// ^(chromium|firefox)$


    4.2 Matching cmdlines with RE patterns

    A good option that allows fine adjustment.

re_match_cmdline = False

@CMDLINE_RE  300 /// -childID|--type=renderer
@CMDLINE_RE -200 /// ^/usr/lib/virtualbox


    4.3 Matching UIDs with RE patterns

    The most slow option

re_match_uid = False

@UID_RE -100 /// ^0$
```
