### ISSUE TITLE
psi2log: to wide columns

### ISSUE THREAD

**Issue by tim77** [hakavlad/nohang#114]
Now `psi2log` have 115 columns which is to much i believe since 80 is de-facto standard. This looks like this on 100 columns terminal:
![Снимок экрана от 2021-01-02 19-36-43](https://user-images.githubusercontent.com/5614476/103464258-fcd21380-4d3a-11eb-88e0-cb22335ea87a.png)
Can we shrink it to 80 or 100 at least? This could improve overall UX.

**Comment by hakavlad** [comment]
Yes.

**Comment by hakavlad** [comment]
BTW, mem2log in your pic. Not psi2log.

**Comment by hakavlad** [comment]
psi2log non-wide mode: psi2log -m2

**Comment by tim77** [comment]
> BTW, mem2log is on your pic. Not psi2log.

Sorry, i wanted suggest to improve both this tools and `mem2log` have similar issue. :) 

> psi2log non-wide mode: psi2log -m2

Great but default behavior maybe could still be improved in some way and look better on 80 columns?

**Comment by hakavlad** [comment]
>look better on 80 columns?

Now it has good look and well-formatted. I'm not sure if a narrower output can be made with mode 1.

**Comment by hakavlad** [comment]
TODO:
```
===============================================================================
     cpu      ||               io              ||            memory
============= || ============================= || =============================
     some     ||      some     |      full     ||      some     |       full
------------- || ------------- | ------------- || ------------- | -------------
 avg10  avg60 ||  avg10  avg60 |  avg10  avg60 ||  avg10  avg60 |  avg10  avg60 
------ ------ || ------ ------ | ------ ------ || ------ ------ | ------ ------ 
100.00 100.00 || 100.00 100.00 | 100.00 100.00 || 100.00 100.00 | 100.00 100.00 
100.00 100.00 || 100.00 100.00 | 100.00 100.00 || 100.00 100.00 | 100.00 100.00 
100.00 100.00 || 100.00 100.00 | 100.00 100.00 || 100.00 100.00 | 100.00 100.00 
100.00 100.00 || 100.00 100.00 | 100.00 100.00 || 100.00 100.00 | 100.00 100.00 
===============================================================================
```
w=89

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/b8983177e645a85ca5107f5842882243619cb00d
