### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Koopiq** [hakavlad/nohang#12]
Ello. I've noticed you don't have a CoC yet. Care to accept one? I would suggest accepting Contributor Covenant's CoC, believe me it's an incredible CoC, everyone should accept it or at least try it. You would be amazed how great of a CoC it is.

Here is how you can accept a CoC: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

Please do, mkay?

**Comment by hakavlad** [comment]
Thank you. Done https://github.com/hakavlad/nohang/blob/master/CoC.md.

**Comment by hakavlad** [comment]
Also good CoC:
https://github.com/domgetter/NCoC/blob/master/CODE_OF_CONDUCT.md

**Comment by Koopiq** [comment]
I don't like your coc.

**Comment by hakavlad** [comment]
>I don't like your coc.

Please, **do not discuss about this CoC**. Sorry.

**Comment by hakavlad** [comment]
I'm not discuss about CoC, I discuss about your CoC violation.

**Comment by Koopiq** [comment]
You cannot discuss coc violation without discussing coc, otherwise it's not clear which coc I've violated. You also cannot enforce your coc without referring to it's rules.

Your coc is flawed.

**Comment by hakavlad** [comment]
I don't discuss about CoC. Mention of CoC is non discussion about CoC. Sorry, I can not answer your arguments, because the discussion of CoC is forbidden.

**Comment by hakavlad** [comment]
>You also cannot enforce your coc without referring to it's rules.

referring is not discussing
