### ISSUE TITLE
Detect and prevent excessive paging/swapping

### ISSUE THREAD

**Issue by joeytwiddle** [hakavlad/nohang#133]
I'm not sure if this is correct, but I will propose it and you see what you think:

- Low RAM and low swap are not really a problem. The problem is when both are low AND the data in swap is wanted by apps, and so pages are constantly being cycled in and out of swap. That is when our system really becomes unresponsive.

So perhaps our goal should not be to trigger on low memory, but instead trigger on high paging activity (and low memory).

Does that make sense?

**Comment by hakavlad** [comment]
I think the PSI is already doing what it needs to do. This is probably a more accurate indicator than swapping.
