### ISSUE TITLE
(Minor) Increase PID justification to 7 characters

### ISSUE THREAD

**Issue by azjps** [hakavlad/nohang#18]
The maximum PID that can be used on 64-bit linux systems is [2^22](https://stackoverflow.com/questions/6294133/maximum-pid-in-linux), can the padding in `oom-sort` be increased to 7 chars for PID or determined from `/proc/sys/kernel/pid_max`? Happy to submit a PR.

**Comment by hakavlad** [comment]
The maximum UID that can be used on 64-bit linux systems is [2^32](https://serverfault.com/questions/105260/how-big-in-bits-is-a-unix-uid).

**Comment by hakavlad** [comment]
Done.
