### ISSUE TITLE
DISPLAY in config

### ISSUE THREAD

**Issue by mikhailnov** [hakavlad/nohang#2]
У вас в конфиге https://github.com/hakavlad/nohang/blob/master/nohang.conf#L217 задается `$DISPLAY`, но вот здесь https://github.com/hakavlad/nohang/commit/b1a6565a99cf2fc78fd1f2d94146bb4872d5b1fd вроде бы DISPLAY берется из `ps ae`.

**Comment by hakavlad** [comment]
Спасибо. Как раз работаю над этим, пока не успел конфиг поправить.

root_display = :0
- это удалю из конфига.

**Comment by hakavlad** [comment]
Problem solved
