### ISSUE TITLE
deb/rpm/PyPI packaging

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#27]
subj

**Comment by hakavlad** [comment]
@yangfl Could you package nohang for Ubuntu and Debian, please?

**Comment by hakavlad** [comment]
Added instructions to make a deb package https://github.com/hakavlad/nohang/commit/17ae2a999630b58593d2d2ca904ecb7a4c9830db

**Comment by hakavlad** [comment]
https://repology.org/project/nohang/versions

**Comment by alexmyczko** [comment]
I have done basic backports of the sid nohang for bionic and focal, they work great. many thanks for the software. (obviously the stock bionic kernel doesn't have PSI support, but they are to get focal anyways)

**Comment by hakavlad** [comment]
Thanks for the feedback!

By the way, nohang 0.1 release version (that was packaged for debian sid) is completely outdated, bugged and has no PSI support. nohang 1.0.0 coming soon, I hope.

**Comment by alexmyczko** [comment]
When will the release come soon? I'm concerned because of https://release.debian.org/bullseye/freeze_policy.html

**Comment by hakavlad** [comment]
oh, I hope this year) maybe in december

Will we make the update in time if the release is in December?

**Comment by hakavlad** [comment]
@yangfl @alexmyczko @FabioPedretti

nohang v0.2.0 released https://github.com/hakavlad/nohang/releases/tag/v0.2.0

Also maybe you want to package new tools (`prelockd`, `memavaild`, `uresourced`), see https://github.com/hakavlad/nohang#solution

**Comment by alexmyczko** [comment]
JFYI: https://mentors.debian.net/package/nohang/

**Comment by FabioPedretti** [comment]
I updated the Ubuntu packages: https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages?field.name_filter=nohang&field.status_filter=published (port of @alexmyczko packages).
