### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by lalten** [hakavlad/nohang#47]
Installing latest git master (c4f6a666eae5700f9df74349cc92bb647261dc23) fails for me (Ubuntu 18.04)
```
$ sudo make install                
install -d /usr/local/bin
install -m0755 nohang /usr/local/bin/nohang
install -m0755 nohang_notify_helper /usr/local/bin/nohang_notify_helper
install -m0755 oom-sort /usr/local/bin/oom-sort
install -m0755 psi-top /usr/local/bin/psi-top
install -m0755 psi-monitor /usr/local/bin/psi-monitor
install -d /etc/nohang
git describe --tags --long --dirty > version
install -m0644 version /etc/nohang/version
rm -fv version
removed 'version'
install -m0644 nohang.conf /etc/nohang/nohang.conf
install -m0644 nohang.conf /etc/nohang/nohang.conf.default
install -d /etc/logrotate.d
install -m0644 nohang.logrotate /etc/logrotate.d/nohang
install -d /usr/share/man/man1
gzip -c nohang.1 > /usr/share/man/man1/nohang.1.gz
gzip -c oom-sort.1 > /usr/share/man/man1/oom-sort.1.gz
install -d /etc/systemd/system
sed "s|:TARGET_BIN:|/usr/local/bin|g;s|:TARGET_CONF:|/etc|g" nohang.service.in > nohang.service
install -m0644 nohang.service /etc/systemd/system/nohang.service
rm -fv nohang.service
removed 'nohang.service'
chcon -t systemd_unit_file_t /etc/systemd/system/nohang.service
chcon: can't apply partial context to unlabeled file '/etc/systemd/system/nohang.service'
Makefile:12: recipe for target 'install' failed
make: [install] Error 1 (ignored)
```

I guess the problem is that
> File context can be temporarily modified with the chcon command. If you want to permanantly change the file context you need to use the semanage fcontext command. This will modify the SELinux labeling database. You will need to use restorecon to apply the labels.

-- https://www.systutorials.com/docs/linux/man/8-system_selinux/

**Comment by hakavlad** [comment]
Thank you for this report!

>I guess the problem is that

Actually no problem:

Case 1:
System with SELinux (Fedora): No error.

Case 2:
System without SELinux (Deb, Ubuntu, Arch): Error will be ignored.

See also https://github.com/rfjakob/earlyoom/issues/129:

>But in any case, an error in setting the context is ignored because of the "-" in front of the line in the Makefile.

Keep calm and sudo make systemd.

**Comment by lalten** [comment]
OK, thank you!
