### ISSUE TITLE
Use /dev/chromeos-low-mem

### ISSUE THREAD

**Issue by mikhailnov** [hakavlad/nohang#53]
ChromiumOS kernel patches include `/dev/chromeos-low-mem` pseudo-device
https://gitlab.freedesktop.org/seanpaul/dpu-staging/commit/0b992f2dbb044896c3584e10bd5b97cf41e2ec6d
(as far as I understood from the changelog, it was previously named `/dev/low-mem`)

That file can be used to detect if system is in low memory condition or not.

Maybe it will be interesting to you. I've never used nohang frankly speaking, just wanted to give an idea...

**Comment by mikhailnov** [comment]
user@rosa2016 ~ $ ls /sys/kernel/mm/chromeos-low_mem/
available  margin  ram_vs_swap_weight
user@rosa2016 ~ $ for i in $(ls /sys/kernel/mm/chromeos-low_mem/*); do echo ; echo $i:; cat $i ; done

/sys/kernel/mm/chromeos-low_mem/available:
4018

/sys/kernel/mm/chromeos-low_mem/margin:
50

/sys/kernel/mm/chromeos-low_mem/ram_vs_swap_weight:
4
user@rosa2016 ~ $ ls /dev/ | grep low
chromeos-low-mem
user@rosa2016 ~ $ cat /dev/chromeos-low-mem
cat: /dev/chromeos-low-mem: Недопустимый аргумент
user@rosa2016 ~ $ file /dev/chromeos-low-mem
/dev/chromeos-low-mem: character special (1/12)

**Comment by mikhailnov** [comment]
Description of these entries can be found here: https://chromium.googlesource.com/chromium/src/+/master/base/util/memory_pressure/system_memory_pressure_evaluator_chromeos.cc#28

**Comment by hakavlad** [comment]
Thank you! 

This patchset is not enabled in most distros, right?

BTW, `/proc/meminfo` and `/proc/pressure/memory` (and `memory.pressure` files in cgroup2) are enough for a complete diagnosis. Nohang can use both right now.

**Comment by mikhailnov** [comment]
Right. Probably yes, it't does not provide any very important information, it just makes some additional calculations and reports results. Those calculations can be done and probably are already done in nohang without that.
