### ISSUE TITLE
sudo: setrlimit(RLIMIT_CORE): Operation not permitted

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#61]
GUI nonifications is broken in nohang-dev-desktop

**Comment by hakavlad** [comment]
not a bug, GUI notifications work fine

**Comment by prajyotkarkade5** [comment]
how did you solved it ?

**Comment by hakavlad** [comment]
See https://github.com/hakavlad/nohang/commit/93a504a5ce23f2960bf7bff28496956ae457d5fe - I've added CAP_SYS_RESOURCE to capabilities list in the systemd unit file.

**Comment by man313-design** [comment]
sudo: setrlimit(RLIMIT_CORE): Operation not permitted

**Comment by hakavlad** [comment]
@man313-design  can I help you?

**Comment by man313-design** [comment]
Yes Sir I need u r help
