### ISSUE TITLE
PPA for Ubuntu based systems

### ISSUE THREAD

**Issue by asoltesz** [hakavlad/nohang#73]
For Ubuntu based systems a PPA with a DEB would be nice. 

That would solve the issue of proper, package based installation/removal on these systems.

Since this is a desktop oriented tool (GUI notification and such) and ATM, desktop is ruled by Ubuntu derivatives, I would argue that this might be a priority in the packaging side.   

----
BTW: Thanks for the hard work, it is greatly appreciated.

**Comment by hakavlad** [comment]
>That would solve the issue of proper, package based installation/removal on these systems.

Added instructions for packaging: https://github.com/hakavlad/nohang/commit/17ae2a999630b58593d2d2ca904ecb7a4c9830db

**Comment by hakavlad** [comment]
@mikhailnov Could you make a PPA for nohang, please?

**Comment by alexmyczko** [comment]
https://launchpad.net/~gagarin/+archive/ubuntu/focal/+packages (there you go, for 20.04, but it's 0.1, which seems to be totally outdated according https://github.com/hakavlad/nohang/issues/27)

**Comment by FabioPedretti** [comment]
Starting from Ubuntu 20.10/groovy (and Debian 11) nohang is included in the official repository!
https://launchpad.net/ubuntu/+source/nohang
https://packages.debian.org/search?keywords=nohang

**Comment by hakavlad** [comment]
Yes, but it is outdated 2018-11 release versions!

**Comment by alexmyczko** [comment]
https://mentors.debian.net/package/nohang/

updated version, mind if i suggest tagging new releases?

**Comment by hakavlad** [comment]
Excellent, thanks!

**Comment by mikhailnov** [comment]
> https://mentors.debian.net/package/nohang/
> 
> updated version, mind if i suggest tagging new releases?

Good luck :-) Debian's bureaucracy when uploading packages is a nightmare.



> @mikhailnov Could you make a PPA for nohang, please?

Sorry, I forgot to answer, I of course can make it, but it would be nice if I started using nohang myself first... Is there a good  comparison with earlyoom somewhere?

**Comment by hakavlad** [comment]
>Is there a good comparison with earlyoom somewhere?

no, only bad  old comparsion https://www.opennet.ru/tips/3116_oomkill_memory_earlyoom_nohang_oomd.shtml

@mikhailnov See also new tools - https://www.linux.org.ru/forum/desktop/15926779 - could you also make a ppa for prelockd and memavaild, please?

**Comment by FabioPedretti** [comment]
> https://mentors.debian.net/package/nohang/
> 
> updated version, mind if i suggest tagging new releases?

I built this for both Ubuntu 20.04/focal and 20.10/groovy, it's available in my test PPA (which also includes a couple other packages):
https://launchpad.net/~oibaf/+archive/ubuntu/test/

**Comment by hakavlad** [comment]
@FabioPedretti thanks! Readme updated: https://github.com/hakavlad/nohang#to-install-on-ubuntu-20042010

Coud you also make a package for 18.04, please?

**Comment by FabioPedretti** [comment]
> @FabioPedretti thanks! Readme updated: https://github.com/hakavlad/nohang#to-install-on-ubuntu-20042010
> 
> Coud you also make a package for 18.04, please?

I pushed it also for 18.04/bionic.

**Comment by FabioPedretti** [comment]
> > @FabioPedretti thanks! Readme updated: https://github.com/hakavlad/nohang#to-install-on-ubuntu-20042010
> > Coud you also make a package for 18.04, please?
> 
> I pushed it also for 18.04/bionic.

Sorry, actually I deleted it, because it failed to build there (needed a newer debhelper and that also failed to build. I could lower the debhelper compat, but anyway I think it's actually better if 18.04 users upgrade to 20.04).

**Comment by hakavlad** [comment]
OK, thanks.
