### ISSUE TITLE
[KDE] notifications "don't deserve to be in history"

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#79]
See https://github.com/rfjakob/earlyoom/issues/139

**Comment by KAMiKAZOW** [comment]
Wrt to this comment: https://github.com/hakavlad/nohang/pull/81#issuecomment-578467721

What exactly is this bug about? If you don't want the notification in the notification history anyway, it's not a bug that it's not in the notification history.

**Comment by hakavlad** [comment]
>What exactly is this bug about?

About notifications history in KDE Plasma 5.16.2+.

`-u critical` is not OK because it can block other new notifications in GNOME, and  this is too intrusive behavior.

**Comment by hakavlad** [comment]
System Settings -> Notifications -> Applications: Configure -> Other Applications -> [+]Show in history

It works in KDE Plasma 5.18.4.
