### ISSUE TITLE
опакетил для AUR-а

### ISSUE THREAD

**Issue by actionless** [hakavlad/nohang#8]
https://aur.archlinux.org/packages/nohang-git/

**Comment by hakavlad** [comment]
Спасибо.
@actionless 
https://aur.archlinux.org/nohang-git.git 
404 - Page Not Found
Is it normal? Я не арчер, не знаю подводных.

**Comment by hakavlad** [comment]
@actionless 

For Arch Linux, there's an AUR package:

yaourt -S nohang-git
sudo systemctl enable nohang-git
sudo systemctl start nohang-git

Это так должно работать?

**Comment by actionless** [comment]
да

только yaourt уже того, вместо него используют pikaur или yay

**Comment by hakavlad** [comment]
@actionless 
>вместо него используют

Есть статистика?

>yaourt уже того

В списке https://wiki.archlinux.org/index.php/AUR_helpers он еще есть

**Comment by actionless** [comment]
он помечен как stalled и не реализует некоторых важных функций (смотри в таблице по приведенной тобой ссылке)

**Comment by hakavlad** [comment]
ок, спасибо

**Comment by hakavlad** [comment]
zfkerr commented on 2018-11-23 20:00

@actionless thank you very much for your work.

nohang first stable release now available here: https://github.com/hakavlad/nohang/releases

I would like to ask you to create an separate AUR package for stable releases other than this git package. Thank you in advance.
https://aur.archlinux.org/packages/nohang-git/

Also procps no longer needed.

Dependencies: python3
Recommended: sudo and libnotify

**Comment by actionless** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=nohang-git&id=f1eff9ad5c71edd5a2f110bf97f35659843f6440

**Comment by hakavlad** [comment]
@actionless 

yaourt -S nohang-git

==> Downloading nohang-git PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
zfkerr commented on 2018-11-23 20:00			 

athost commented on 2018-12-16 14:35			 

actionless commented on 2018-12-16 14:42			 

actionless commented on 2018-12-16 14:43			 

nohang-git 0.1.r85.g74640fe-1  (2018-12-16 05:05)
**( Unsupported package: Potentially dangerous ! )**
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> 

WTF? (on Manjaro)
Почему Unsupported?

**Comment by actionless** [comment]
```
pacman  -Ql nohang-git
nohang-git /etc/
nohang-git /etc/nohang/
nohang-git /etc/nohang/nohang.conf
nohang-git /etc/nohang/nohang.conf.backup
nohang-git /usr/
nohang-git /usr/bin/
nohang-git /usr/bin/nohang
nohang-git /usr/bin/nohang_notify_helper
nohang-git /usr/bin/oom-sort
nohang-git /usr/bin/oom-trigger
nohang-git /usr/lib/
nohang-git /usr/lib/systemd/
nohang-git /usr/lib/systemd/system/
nohang-git /usr/lib/systemd/system/nohang.service
nohang-git /usr/share/
nohang-git /usr/share/man/
nohang-git /usr/share/man/man1/
nohang-git /usr/share/man/man1/nohang.1.gz
nohang-git /usr/share/man/man1/oom-sort.1.gz
nohang-git /usr/share/man/man1/oom-trigger.1.gz
```

**Comment by actionless** [comment]
yaourt is unsupported, please use pikaur instead

**Comment by hakavlad** [comment]
thanks

**Comment by hakavlad** [comment]
zfkerr commented on 2019-03-22 14:13
@actionless Makepkg was unable to build nohang-git:

==> Starting package()...
make: the '-j' option requires a positive integer argument
/bin/sh: /etc/nohang/version: Permission denied
install -d /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///usr/sbin
install -m0755 ./nohang /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///usr/sbin/nohang
install -m0755 ./nohang_notify_helper /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///usr/sbin/nohang_notify_helper
install -d /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///usr/bin
install -m0755 ./oom-sort /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///usr/bin/oom-sort
install -d /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///etc/nohang
install -m0644 ./nohang.conf /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///etc/nohang/
install -m0644 ./nohang.conf /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///etc/nohang/nohang.conf.default
install -m0644 ./nohang.logrotate /tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///etc/logrotate.d/nohang
install: cannot create regular file '/tmp/yaourt-tmp-user/aur-nohang-git/pkg/nohang-git///etc/logrotate.d/nohang': No such file or directory
make: *** [Makefile:16: install] Error 1
==> ERROR: A failure occurred in package().
Aborting...
https://aur.archlinux.org/packages/nohang-git/

**Comment by hakavlad** [comment]
@actionless Maybe it was fixed by https://github.com/hakavlad/nohang/commit/2e612c02b6976794ba53784a2041a3a43220b924

**Comment by actionless** [comment]
yup, it was, thanks!

**Comment by hakavlad** [comment]
@actionless 
Поправил makefile в соответствии c рекомендациями man hier

А потом случилось ЭТО:
```
make: [Makefile:31: install] Error 1 (ignored)
mv: cannot stat 'usr/sbin/*': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: nohang-git
```

http://okturing.com/src/6593/body

**Comment by hakavlad** [comment]
Also
A highly configurable OOM preventer
->
A highly configurable OOM prevention daemon

**Comment by hakavlad** [comment]
@actionless исправь всё плиз

**Comment by actionless** [comment]
guess you need first to fix your makefile

as to package description update, what's your nickname in AUR, i can just set you as a co-maintainer of this https://aur.archlinux.org/packages/nohang-git so you could easily push such updates

**Comment by actionless** [comment]
ah, regarding usr/bin, my bad, it's indeed happening in PKGBUILD itself, i forgot what i had to adjust from ubuntu/deb layout to arch

i'll push now a fix

**Comment by actionless** [comment]
done: https://aur.archlinux.org/cgit/aur.git/commit/?h=nohang-git&id=668885f4364e52fca568772b5293adce6b7f6b2a

**Comment by actionless** [comment]
and https://aur.archlinux.org/cgit/aur.git/commit/?h=nohang-git&id=adf8a078a6c5da6902e1c04ecae9b58b43692951

**Comment by hakavlad** [comment]
@actionless thank you!

**Comment by hakavlad** [comment]
@actionless 

```
Jul 22 18:25:42 user-pc systemd[1]: Started Highly configurable OOM prevention daemon.
Jul 22 18:25:49 user-pc nohang[439]: config: /etc/nohang/nohang.conf
Jul 22 18:25:49 user-pc nohang[439]: Monitoring has started!
Jul 22 18:28:02 user-pc systemd[1]: nohang.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

Can we fix it?

BTW
```
[Service]
ExecStart=/usr/local/bin/nohang --config /etc/nohang/nohang.conf
```

- /usr/local/bin/nohang instead of  /usr/bin/nohang

**Comment by hakavlad** [comment]
@actionless 

```
$ pikaur -S nohang-git
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 nohang-git                                                 -> 0.1.r413.gaf36cb2-2

:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
looking for conflicting AUR packages...
:: warning: Not showing diff for nohang-git package (already reviewed)
Do you want to edit PKGBUILD for nohang-git package? [y/N] n

:: Downloading the latest sources for a devel package nohang-git...
:: Package nohang-git is already built. Pass '--rebuild' flag to force the build.

loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) nohang-git-0.1.r413.gaf36cb2-2

Total Installed Size:  0.18 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                     [####################################################################] 100%
(1/1) checking package integrity                                                                                   [####################################################################] 100%
(1/1) loading package files                                                                                        [####################################################################] 100%
(1/1) checking for file conflicts                                                                                  [####################################################################] 100%
(1/1) checking available disk space                                                                                [####################################################################] 100%
:: Processing package changes...
(1/1) installing nohang-git                                                                                        [####################################################################] 100%
Optional dependencies for nohang-git
    libnotify: to show GUI notifications [installed]
    sudo: to show GUI notifications if nohang started with UID=0 [installed]
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...
[user@user-pc ~]$ sudo systemctl status nohang
● nohang.service - Highly configurable OOM prevention daemon
   Loaded: loaded (/usr/lib/systemd/system/nohang.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:nohang(1)
           https://github.com/hakavlad/nohang
[user@user-pc ~]$ sudo systemctl start nohang
[user@user-pc ~]$ sudo systemctl status nohang
● nohang.service - Highly configurable OOM prevention daemon
   Loaded: loaded (/usr/lib/systemd/system/nohang.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-07-23 07:15:10 EDT; 11s ago
     Docs: man:nohang(1)
           https://github.com/hakavlad/nohang
  Process: 2337 ExecStart=/usr/local/bin/nohang --config /etc/nohang/nohang.conf (code=exited, status=203/EXEC)
 Main PID: 2337 (code=exited, status=203/EXEC)

Jul 23 07:15:09 user-pc systemd[1]: Stopped Highly configurable OOM prevention daemon.
Jul 23 07:15:09 user-pc systemd[1]: Started Highly configurable OOM prevention daemon.
Jul 23 07:15:09 user-pc systemd[1]: nohang.service: Main process exited, code=exited, status=203/EXEC
Jul 23 07:15:09 user-pc systemd[1]: nohang.service: Failed with result 'exit-code'.
Jul 23 07:15:10 user-pc systemd[1]: nohang.service: Service RestartSec=100ms expired, scheduling restart.
Jul 23 07:15:10 user-pc systemd[1]: nohang.service: Scheduled restart job, restart counter is at 5.
Jul 23 07:15:10 user-pc systemd[1]: Stopped Highly configurable OOM prevention daemon.
Jul 23 07:15:10 user-pc systemd[1]: nohang.service: Start request repeated too quickly.
Jul 23 07:15:10 user-pc systemd[1]: nohang.service: Failed with result 'exit-code'.
Jul 23 07:15:10 user-pc systemd[1]: Failed to start Highly configurable OOM prevention daemon.
```

**Comment by hakavlad** [comment]
TODO: use  `sed`

**Comment by hakavlad** [comment]
fixed
https://github.com/hakavlad/nohang/commit/cfe68fcca5eeed28417663f7d3beba36ebf703cc
https://github.com/hakavlad/nohang/commit/478b640135c49ed170debd6a85926e972f8177ac

**Comment by hakavlad** [comment]
@actionless  Is it time to upgrade the package version?

**Comment by actionless** [comment]
idk, if you feel like it

i usually do it every couple of month if have at least around ten of useful commits

**Comment by hakavlad** [comment]
```
backup=('etc/nohang/nohang.conf')
```

The demon now has two config: nohang.conf and nohang-desktop.conf

Could you add a 2nd config to the backup?

**Comment by hakavlad** [comment]
It may also be worth adding a logrotate depending: maintaining a separate log is one of the options.

**Comment by actionless** [comment]
added

**Comment by actionless** [comment]
however adding one more config file to setup IMHO worth pushing version to 0.2

**Comment by hakavlad** [comment]
Thank you! 0.2 coming soon.
