### ISSUE TITLE
Setting memory limits by cgroup

### ISSUE THREAD

**Issue by rramabadran** [hakavlad/nohang#99]
Can cgroup controllers be used to set memory limits, as well? Or are only the holistic memory limits part of the config file to be used with nohang?

**Comment by hakavlad** [comment]
>Can cgroup controllers be used to set memory limits, as well?

You can set memory limits with systemd for systemd units. For example, nohang has set limits for itself via systemd unit:
```
MemoryMax=100M
MemorySwapMax=100M
```
https://github.com/hakavlad/nohang/blob/master/systemd/nohang.service.in

See also https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html

**Comment by hakavlad** [comment]
>Or are only the holistic memory limits part of the config file to be used with nohang?

Yes. nohang can't set memory limits for cgroups. nohangs uses `MemAvailable` and `SwapFree` from `/proc/meminfo` and Pressure Stall Information metrics from `/proc/pressure/memory`.

**Comment by hakavlad** [comment]
Using `systemd-run` you can set limits for running applications. For example,
```
$ systemd-run --user -p MemoryMax=1G -p MemorySwapMax=0 tail /dev/zero
```
Maybe it needs cgroup_v2 to be mounted via passing `systemd.unified_cgroup_hierarchy=1 swapaccount=1` in the kernel boot cmdline. Also set `DefaultMemoryAccounting=true` in `/etc/systemd/system.conf`.

**Comment by hakavlad** [comment]
@rramabadran I'm sorry to be late with the reply.
